### ISSUE TITLE
oc8-specific Roadmap

### ISSUE THREAD

**Issue by VicDeo** [owncloud/documents#417]
- [x] Show user up only once in the sidebar, even with the doc open in multiple tabs 
PR: https://github.com/owncloud/documents/pull/405 
issue: https://github.com/owncloud/documents/issues/125

- [x] Change zoom to combobox instead of slider
PR: https://github.com/owncloud/documents/pull/370
issue: https://github.com/owncloud/documents/issues/123

- [x] Cleanup orphaned code from previous versions
PRs
https://github.com/owncloud/documents/pull/383
https://github.com/owncloud/documents/pull/387
https://github.com/owncloud/documents/pull/394
https://github.com/owncloud/documents/pull/398

- [x] New header bar
issue: https://github.com/owncloud/documents/issues/126
PR: https://github.com/owncloud/documents/pull/415

- [x] Sync with the  WebODF 0.5.7. Done for OC 8.1
PR: https://github.com/owncloud/documents/pull/492

====
- [ ] Chat integration (sidebar in the chat app )
issue: https://github.com/owncloud/documents/issues/137
